# Generated by Django 4.2.11 on 2025-04-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('was_automated', models.BooleanField(default=True)),
                ('backup_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
