# Generated by Django 4.2.11 on 2025-04-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='latitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='longitude',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
