# Generated by Django 5.1.6 on 2025-04-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_packinglistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitRecommendation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('weather_condition', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('outfit_description', models.TextField()),
                ('is_customized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_recommendations', to='trips.trip')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
    ]
