# Generated by Django 5.1.6 on 2025-04-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_outfitrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfitrecommendation',
            name='activities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='outfitrecommendation',
            name='cultural_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trips.outfitrecommendation')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
