# Generated by Django 5.1.6 on 2025-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_outfitrecommendation_activities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinglistitem',
            name='must_have',
            field=models.BooleanField(default=False),
        ),
    ]
