# Generated by Django 5.2 on 2025-04-27 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_packinglistitem_must_have'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelTip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('Travel', 'Travel'), ('Cultural', 'Cultural'), ('Safety', 'Safety'), ('Other', 'Other')], default='Travel', max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='trips.trip')),
            ],
        ),
    ]
